version: '3.8'

services:
  
  server:
    image: ghcr.io/silkkycloud/nitter:latest
    hostname: nitter
    networks:
      - public
      - backend
      - proxy_net
    deploy:
      mode: replicated
      replicas: 3
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.labels.web_server == true"
      update_config:
        failure_action: rollback
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.1'
          memory: 256M
      labels:
        - "traefik.enable=true"
        # Router
        - "traefik.http.routers.nitter.rule=Host(`${HOSTNAME}`)"
        - "traefik.http.routers.nitter.entrypoints=websecure"
        - "traefik.http.routers.nitter.tls=true"
        - "traefik.http.routers.nitter.middlewares=nitter-headers"
        - "traefik.http.routers.nitter.service=nitter-service"
        # Middleware
        - "traefik.http.middlewares.nitter-headers.headers.framedeny=true"
        # Service
        - "traefik.http.services.nitter-service.loadbalancer.server.port=8080"
        - "traefik.http.services.nitter-service.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.nitter-service.loadbalancer.sticky.cookie.secure=true"
        - "traefik.http.services.nitter-service.loadbalancer.sticky.cookie.samesite=strict"
    environment:
      - HMAC_KEY=${HMAC_KEY}

  redis:
    image: redis:6.2.6-alpine
    hostname: redis
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 50M

networks:
  public:
    external: true
  proxy_net:
    external: true

  backend:
    driver: overlay
    internal: true
    driver_opts:
      encrypted: "true"
      com.docker.network.driver.mtu: 1450